system: invincible-gtg

service: omniman-service

deployment:
  image:
    repository: tferrari92/omniman-service # This value was modified by the initial-setup script
    
  labels:
    system: invincible-gtg
    service: omniman-service
    backstage.io/kubernetes-id: omniman-service
